name: Run test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run tests
        env:
          YUNDICT_API_TOKEN: ${{ secrets.YUNDICT_API_TOKEN }}
          YUNDICT_API_ENDPOINT: ${{ secrets.YUNDICT_API_ENDPOINT }}
        run: bun test
